export const INDUSTRIAS = [
  { label: "Ecommerce / Tienda online", value: "ecommerce" },
  { label: "Ropa y calzado", value: "ropa_calzado" },
  { label: "Restaurante o comida rápida", value: "restaurante_comida_rapida" },
  { label: "Artículos de belleza", value: "articulos_belleza" },
  { label: "Kiosco", value: "kiosco" },
  { label: "Minimercado", value: "minimercado" },
  { label: "Electrónica e informática", value: "electronica_informatica" },
  { label: "Industria o manufactura", value: "industria_manufactura" },
  { label: "Farmacia y droguería", value: "farmacia_drogueria" },
  { label: "Tienda de mascotas o vet", value: "mascotas_veterinaria" },
  { label: "Puertas y aberturas", value: "aberturas" },
  { label: "Ferretería y construcción", value: "ferreteria_construccion" },
  { label: "Papelería y libros", value: "papeleria_libros" },
  { label: "Licorería", value: "licoreria" },
  { label: "Hoteles y turismo", value: "hoteles_turismo" },
  { label: "Cafetería", value: "cafeteria" },
  { label: "Bar", value: "bar" },
  { label: "Transporte y logística", value: "transporte_logistica" },
  { label: "Artículos para el hogar", value: "articulos_hogar" },
  { label: "Panadería y Repostería", value: "panaderia_reposteria" },
  { label: "Taller automotriz", value: "taller_automotriz" },
  { label: "Marketing y publicidad", value: "marketing_publicidad" },
  { label: "Artículos deportivos", value: "articulos_deportivos" },
  { label: "Gimnasio", value: "gimnasio" },
  { label: "Tatuajes y piercings", value: "tatuajes_piercings" },
  { label: "Reparaciones y mantenimiento", value: "reparaciones_mantenimiento" },
  { label: "Servicios educativos", value: "servicios_educativos" },
  { label: "Organización de eventos", value: "organizacion_eventos" },
  { label: "Estética y salud", value: "estetica_salud" },
  { label: "Barbería y salón de belleza", value: "barberia_salon" },
  { label: "Préstamos y financiamiento", value: "prestamos_financiamiento" },
  { label: "Tienda naturista y/o suplementos", value: "naturista_suplementos" },
  { label: "Entretenimiento y ocio", value: "entretenimiento_ocio" },
  { label: "Venta de automóviles", value: "venta_automoviles" },
  { label: "Artículos automotrices", value: "articulos_automotrices" },
  { label: "Insumos agropecuarios", value: "insumos_agropecuarios" },
  { label: "Carnicería", value: "carniceria" },
  { label: "Fiambrería", value: "fiambreria" },
  { label: "Distribuidora / Mayorista", value: "distribuidora_mayorista" },
  { label: "Accesorios y bisutería", value: "accesorios_bisuteria" },
  { label: "Tiendas de regalos", value: "tiendas_regalos" },
  { label: "Otro", value: "otro" },
];
